name: Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review

jobs:
  unit_tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v
